# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.TextField(default='', null=True),
        ),
    ]
